### ISSUE TITLE
Output Sometimes Appears Duplicated

### ISSUE THREAD

**Issue by mfiano** [Shinmera/verbose#2] opened 2016-08-28 05:36 UTC
I had someone look into the issue of duplicated log lines and/or overwriting the stream that I've reported to you a few times. He can also easily reproduce the issue.

After inspection of your code, you appear to write to _standard-output_ in the controller-loop thread. The REPL itself also writes to this stream. Since the _standard-output_ stream is exactly the same between them (even if you copied the binding), I don't understand how that can not cause problems. Streams do buffering and all kinds of stuff, and are not thread-safe like this. In C, this would be like using a FILE structure abstraction over an fd. If multiple threads JUST wrote to the same fd directly, then you'll get interleaved data, but if they wrote to the same FILE abstraction, then you can get copied buffers, repeated/lost messages, all kinds of stuff.

There aren't many nice ways to fix the code. There are two ways to fix it: A) supply a STREAM which emits to a file and is owned solely by the logging thread, B) your code stores the messages in a queue, and you have to periodically query the queue in your main thread and emit the data.

**Comment by Shinmera** [comment] 2016-08-28 07:24
I don't see why the comparison to C should be applicable here; after all the standard doesn't say anything about threads in one way or the other so they may be safe to write to from threads or not. This is further complicated by the fact that SLIME does its own thing. Given that I've never been able to reproduce your issue myself, I would say that further investigation into the underlying code bases such as SLIME and SBCL are necessary in order to determine what can actually be done about this.

Both of the suggestions you've made are not really solutions or fixes at all. They would fundamentally change how the library works and render it practically useless for the purposes it's been intended for so far.

**Comment by psilord** [comment] 2016-08-28 08:42
Here is a possible way to reproduce it. Since it looks like a race condition, you'll need to tinker with the sleep argument in the form I'm about to supply until it breaks for you. I'm using sbcl 1.3.6 on Linux Mint 17 on x86-64. I'm running sbcl at the bare shell with only enough sbclrc to load quicklisp and with no slime or anything. You can see here there is worse going on that just interleaving of output. Just keep messing with the sleep value until you get the REPL to emit the return value of the
form and the prompt to *standard-output* while the :verbose thread is emitting to *standard-output*.

```lisp

Linux violet > sbcl 
This is SBCL 1.3.6, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:quickload :verbose)
To load "verbose":
  Load 1 ASDF system:
    verbose
; Loading "verbose"
.
(:VERBOSE)
* (setf (v:repl-level) :debug)

:DEBUG
* (loop for i from 0 below 8 do (v:info :ecs.gob.add "v:info iter= ~A" i) (v:info :ecs.gob.add "v:debug iter=~A~%" i)) (sleep .25)

LOG: 2016-08-28 03:39:24 [
LOG: 2016-08-28 03:39:24 [
INFO ] <ECS.GOB.ADD>: v:info iter= 0
NIL
* * 
LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:debug iter=0

LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:info iter= 1
LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:debug iter=1

LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:info iter= 2
LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:debug iter=2

LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:info iter= 3
LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:debug iter=3

LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:info iter= 4
LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:debug iter=4

LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:info iter= 5
LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:debug iter=5

LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:info iter= 6
LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:debug iter=6

LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:info iter= 7
LOG: 2016-08-28 03:39:24 [INFO ] <ECS.GOB.ADD>: v:debug iter=7

NIL

**Comment by mfiano** [comment] 2016-08-29 03:55
Indeed. I too noticed this not to be a problem with SLIME/Sly, as it occurs in a bare SBCL REPL. I don't think this is ever going to work without some major changes after looking at the codebase, with the REPL and this library fighting over the same thread for *standard-output*.

**Comment by Shinmera** [comment] 2016-08-29 06:58
One potential solution is to replace the standard-output stream on every thread with a verbose-made one that synchronises output to a single thread. I'll have to look into that.

**Comment by psilord** [comment] 2016-08-29 16:57
I do have a question about the intended use of this library. When I use a library like this, I use it for both logging what is going on in a general case and debugging. Usually, logs are looked at when something went wrong. :) Now, if the messages are asynchronously being queued into a thread, the point at which the main-thread (suppose that is the only one computing my application code) initiates a log emission is much farther from when I might see that emission. 

So, in an execution scenario like:

 ;; First, a happy ordering.
 0. In main-thread: Emit log line "About to quxify()."
 1. In logging-thread: Message is queued.
 2. In logging-thread: Message is emitted. User sees message.
 3. In main-thread: quxify() is called.

 ;; Now, an unhappy ordering.
 4. In main-thread: Emit log line "About to frobnicate() lossage."
 5. In logging-thread: Message is queued.
 6. In main-thread: Use CFFI call frobnicate() in a C library.
 7. In main-thread: C library segfaults and takes image with it.

Since the message was still in the queue when the segfault happened, I never see it. I will have seen "About to quckify()." so I'd start looking around quxify() in order to find out what went wrong.  Now I have a red herring about why the image failed due to whatever last messages managed to get out before the destruction of the image due to the segfault.

I think that the asynchronous handling of the logging messages here actually would CAUSE problems in trying to find out what went wrong. While I understand that interleaving CPU and I/O is usually a strong win, doing it here stands in opposition to the reason why someone would want the logging information in the first place.

A logging system, in my humble opinion, should emit and sync the message ASAP to wherever it is destined. If this is slow, then turn down the logging. This is really the only recourse in order to have the log lines match up with the code flow to debug when something goes wrong. 

If you insist upon keeping it the way it is, then I suggest adding a new set of apis like V:INFO-FLUSH, etc which perform the action in the thread calling the function. Then you can have the best of both worlds.

**Comment by Shinmera** [comment] 2016-08-29 18:37
Whenever you queue a message the handling thread is immediately awakened through the monitor. This should happen as quickly as it is possible to awaken a thread. The thread also immediately keeps on processing messages for as long as possible until it is 100% sure there are no further ones. It also makes a good effort to keep blocking to an absolute minimum by keeping a back-queue while processing.

One of the primary reasons why Verbose even keeps a separate thread is because otherwise in applications that log and use threads themselves the interleaving effect you've seen is far, far worse and made things pretty much unreadable.

I could add something that processes the message queue immediately in your own thread, if that is something you want/need, or something that blocks until all messages have been processed by the back thread. That actually sounds like a very useful thing to have, but I'll have to think on it for a bit.

**Comment by psilord** [comment] 2016-08-29 23:50
I think something like (setf v:*sync-immediately* t) and then the message is logged/flushed in the same thread which called the API call would be sufficient. It would be a fast path, and an easy thing to turn on for those who don't want to pay for threading. And, you can bind it as a real special so a call path would do the right thing in the right dynamic environment.

**Comment by Shinmera** [comment] 2016-08-30 08:04
You can already force verbose to log from your local thread by simply shutting down the global controller: `(v:stop-controller v:*global-controller*)`

However, I'll add a special to allow controlling the behaviour in a dynamic environment as well.

**Comment by Shinmera** [comment] 2016-08-30 08:12
I still want to add a sync or flush command, but that's proving a bit more tricky.

**Comment by Shinmera** [comment] 2016-08-30 09:23
Ok, if you could test the changes and confirm if they do what you need, that'd be super.

**Comment by Shinmera** [comment] 2017-05-18 15:14
Closing this for now to keep the issues clean. If the added features still don't resolve your issues, please re-open or create a new, more specific ticket.

**Closed by Shinmera** 2017-05-18 15:14 UTC
Labels: bug
